// <auto-generated />
using System;
using HoldMaintenance.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HoldMaintenance.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HoldMaintenance.Api.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WarrantyExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = "a1",
                            AssetCode = "LT001",
                            AssetName = "Dell Latitude 5440",
                            AssetType = "Laptop",
                            AssignedUser = "Nguyễn Văn Quản",
                            Department = "IT",
                            Note = "Thiết bị cấp cho IT Manager",
                            PurchaseDate = new DateTime(2025, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a2",
                            AssetCode = "LT002",
                            AssetName = "MacBook Pro M3",
                            AssetType = "Laptop",
                            AssignedUser = "Admin IT",
                            Department = "IT",
                            Note = "Thiết bị phát triển ứng dụng",
                            PurchaseDate = new DateTime(2025, 12, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 12, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a3",
                            AssetCode = "MN001",
                            AssetName = "Dell UltraSharp 24\"",
                            AssetType = "Màn hình",
                            AssignedUser = "Lê Hoàng Hỗ Trợ",
                            Department = "IT",
                            Note = "Màn hình phụ bàn làm việc",
                            PurchaseDate = new DateTime(2024, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a4",
                            AssetCode = "PR001",
                            AssetName = "Canon LBP2900",
                            AssetType = "Máy in",
                            AssignedUser = "Đỗ Quốc Vận Hành",
                            Department = "Operations",
                            Note = "Máy in văn phòng chung",
                            PurchaseDate = new DateTime(2023, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            WarrantyExpiry = new DateTime(2025, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a5",
                            AssetCode = "LT003",
                            AssetName = "Lenovo ThinkPad T14",
                            AssetType = "Laptop",
                            AssignedUser = "Đỗ Quốc Vận Hành",
                            Department = "Operations",
                            Note = "Thiết bị cá nhân làm việc",
                            PurchaseDate = new DateTime(2025, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a6",
                            AssetCode = "LT004",
                            AssetName = "HP ProBook 450",
                            AssetType = "Laptop",
                            AssignedUser = "Trần Thị Tuyển",
                            Department = "HR",
                            Note = "Laptop hành chính nhân sự",
                            PurchaseDate = new DateTime(2025, 10, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 10, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a7",
                            AssetCode = "LT005",
                            AssetName = "Dell Vostro 3520",
                            AssetType = "Laptop",
                            AssignedUser = "Phạm Minh Bán",
                            Department = "Sales",
                            Note = "Laptop cho kinh doanh",
                            PurchaseDate = new DateTime(2026, 3, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 3, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a8",
                            AssetCode = "MN002",
                            AssetName = "LG Ergo 27\"",
                            AssetType = "Màn hình",
                            AssignedUser = "Trần Thị B",
                            Department = "HR",
                            Note = "Màn hình thiết kế nhân sự",
                            PurchaseDate = new DateTime(2025, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a9",
                            AssetCode = "PR002",
                            AssetName = "HP LaserJet Pro",
                            AssetType = "Máy in",
                            AssignedUser = "",
                            Department = "HR",
                            Note = "Máy in màu dự phòng",
                            PurchaseDate = new DateTime(2024, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            WarrantyExpiry = new DateTime(2027, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a10",
                            AssetCode = "RT001",
                            AssetName = "Cisco Router ISR4331",
                            AssetType = "Thiết bị mạng",
                            AssignedUser = "",
                            Department = "IT",
                            Note = "Router lõi phòng server",
                            PurchaseDate = new DateTime(2022, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2024, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a11",
                            AssetCode = "LT006",
                            AssetName = "MacBook Air M2",
                            AssetType = "Laptop",
                            AssignedUser = "Nguyễn Văn A",
                            Department = "Sales",
                            Note = "Laptop kinh doanh ngoài văn phòng",
                            PurchaseDate = new DateTime(2025, 7, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            WarrantyExpiry = new DateTime(2027, 7, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "a12",
                            AssetCode = "MN003",
                            AssetName = "Samsung Odyssey G5",
                            AssetType = "Màn hình",
                            AssignedUser = "",
                            Department = "Sales",
                            Note = "Màn hình demo sản phẩm",
                            PurchaseDate = new DateTime(2026, 4, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            WarrantyExpiry = new DateTime(2028, 4, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HoldMaintenance.Api.Entities.AssetAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetAssignments");

                    b.HasData(
                        new
                        {
                            Id = "asg1",
                            AssetId = "a1",
                            AssignedDate = new DateTime(2025, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát ban đầu",
                            UserId = "u2",
                            UserName = "Nguyễn Văn Quản"
                        },
                        new
                        {
                            Id = "asg2",
                            AssetId = "a2",
                            AssignedDate = new DateTime(2025, 12, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát máy mới M3",
                            UserId = "u1",
                            UserName = "Admin IT"
                        },
                        new
                        {
                            Id = "asg3",
                            AssetId = "a3",
                            AssignedDate = new DateTime(2024, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát màn hình làm việc",
                            UserId = "u3",
                            UserName = "Lê Hoàng Hỗ Trợ"
                        },
                        new
                        {
                            Id = "asg4",
                            AssetId = "a5",
                            AssignedDate = new DateTime(2025, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát ThinkPad",
                            UserId = "u6",
                            UserName = "Đỗ Quốc Vận Hành"
                        },
                        new
                        {
                            Id = "asg5",
                            AssetId = "a6",
                            AssignedDate = new DateTime(2025, 10, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát máy làm việc chính",
                            UserId = "u4",
                            UserName = "Trần Thị Tuyển"
                        },
                        new
                        {
                            Id = "asg6",
                            AssetId = "a7",
                            AssignedDate = new DateTime(2026, 3, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát làm việc kinh doanh",
                            UserId = "u5",
                            UserName = "Phạm Minh Bán"
                        },
                        new
                        {
                            Id = "asg7",
                            AssetId = "a8",
                            AssignedDate = new DateTime(2025, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát màn hình Ergo",
                            UserId = "u8",
                            UserName = "Trần Thị B"
                        },
                        new
                        {
                            Id = "asg8",
                            AssetId = "a11",
                            AssignedDate = new DateTime(2025, 7, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp phát MacBook Air di động",
                            UserId = "u7",
                            UserName = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = "asg9",
                            AssetId = "a4",
                            AssignedDate = new DateTime(2023, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Cấp máy in phòng Operations",
                            UserId = "u6",
                            UserName = "Đỗ Quốc Vận Hành"
                        });
                });

            modelBuilder.Entity("HoldMaintenance.Api.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = "notif1",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Yêu cầu 'Màn hình MN002 xuất hiện sọc dọc màu xanh' đang chờ IT duyệt và bàn giao.",
                            RelatedId = "t3",
                            Title = "Có yêu cầu hỗ trợ mới cần duyệt",
                            Type = 0,
                            UserId = "u2"
                        },
                        new
                        {
                            Id = "notif2",
                            CreatedAt = new DateTime(2026, 6, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Bạn đã được phân công xử lý yêu cầu 'Laptop Dell LT005 không kết nối được WiFi văn phòng'.",
                            RelatedId = "t2",
                            Title = "Bàn giao công việc mới",
                            Type = 3,
                            UserId = "u3"
                        });
                });

            modelBuilder.Entity("HoldMaintenance.Api.Entities.SupportNote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandledBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SupportNotes");

                    b.HasData(
                        new
                        {
                            Id = "n1",
                            AssetId = "a4",
                            Content = "Đã kiểm tra khay giấy và gỡ giấy kẹt. Đã vệ sinh trục cuốn cao su bằng cồn chuyên dụng.",
                            CreatedAt = new DateTime(2026, 6, 21, 6, 0, 0, 0, DateTimeKind.Utc),
                            HandledBy = "Lê Hoàng Hỗ Trợ",
                            TicketId = "t1"
                        },
                        new
                        {
                            Id = "n2",
                            AssetId = "a4",
                            Content = "Đã hoàn thành xử lý yêu cầu hỗ trợ. Test in thử 10 bản chạy tốt.",
                            CreatedAt = new DateTime(2026, 6, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            HandledBy = "Lê Hoàng Hỗ Trợ",
                            TicketId = "t1"
                        },
                        new
                        {
                            Id = "n3",
                            AssetId = "a7",
                            Content = "Đã cập nhật driver card mạng không dây và cấu hình lại địa chỉ IP tĩnh để test.",
                            CreatedAt = new DateTime(2026, 6, 25, 6, 0, 0, 0, DateTimeKind.Utc),
                            HandledBy = "Lê Hoàng Hỗ Trợ",
                            TicketId = "t2"
                        });
                });

            modelBuilder.Entity("HoldMaintenance.Api.Entities.SupportTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Requester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SupportTickets");

                    b.HasData(
                        new
                        {
                            Id = "t1",
                            AssetId = "a4",
                            AssetName = "Canon LBP2900",
                            AssignedTo = "Lê Hoàng Hỗ Trợ",
                            CompletedAt = new DateTime(2026, 6, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kẹt giấy ở khay nạp và ra nhiệt. Cần bảo trì vệ sinh trục cuốn.",
                            Priority = 1,
                            Requester = "Đỗ Quốc Vận Hành",
                            Status = 2,
                            Title = "Máy in Canon PR001 bị kẹt giấy liên tục"
                        },
                        new
                        {
                            Id = "t2",
                            AssetId = "a7",
                            AssetName = "Dell Vostro 3520",
                            AssignedTo = "Lê Hoàng Hỗ Trợ",
                            CreatedAt = new DateTime(2026, 6, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Máy tính nhận sóng WiFi nhưng báo No Internet, các thiết bị khác hoạt động bình thường.",
                            Priority = 2,
                            Requester = "Phạm Minh Bán",
                            Status = 1,
                            Title = "Laptop Dell LT005 không kết nối được WiFi văn phòng"
                        },
                        new
                        {
                            Id = "t3",
                            AssetId = "a8",
                            AssetName = "LG Ergo 27\"",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình hiển thị sọc dọc đứng màu xanh lá ở góc phải màn hình, đã thử đổi cáp HDMI nhưng không hết.",
                            Priority = 2,
                            Requester = "Trần Thị B",
                            Status = 0,
                            Title = "Màn hình MN002 xuất hiện sọc dọc màu xanh"
                        },
                        new
                        {
                            Id = "t4",
                            AssetId = "a12",
                            AssetName = "Samsung Odyssey G5",
                            CreatedAt = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng kinh doanh cần thêm màn hình phụ MN003 để lắp đặt tại bàn làm việc demo sản phẩm.",
                            Priority = 0,
                            Requester = "Phạm Minh Bán",
                            Status = 0,
                            Title = "Yêu cầu cấp phát màn hình Samsung MN003 cho phòng Sales"
                        });
                });

            modelBuilder.Entity("HoldMaintenance.Api.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "u1",
                            Department = "IT",
                            Email = "admin@company.vn",
                            IsLocked = false,
                            Name = "Admin IT",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 2
                        },
                        new
                        {
                            Id = "u2",
                            Department = "IT",
                            Email = "manager.it@company.vn",
                            IsLocked = false,
                            Name = "Nguyễn Văn Quản",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 2
                        },
                        new
                        {
                            Id = "u3",
                            Department = "IT",
                            Email = "support.it@company.vn",
                            IsLocked = false,
                            Name = "Lê Hoàng Hỗ Trợ",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 1
                        },
                        new
                        {
                            Id = "u4",
                            Department = "HR",
                            Email = "manager.hr@company.vn",
                            IsLocked = false,
                            Name = "Trần Thị Tuyển",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 0
                        },
                        new
                        {
                            Id = "u5",
                            Department = "Sales",
                            Email = "manager.sales@company.vn",
                            IsLocked = false,
                            Name = "Phạm Minh Bán",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 0
                        },
                        new
                        {
                            Id = "u6",
                            Department = "Operations",
                            Email = "manager.ops@company.vn",
                            IsLocked = false,
                            Name = "Đỗ Quốc Vận Hành",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 0
                        },
                        new
                        {
                            Id = "u7",
                            Department = "Sales",
                            Email = "employee1@company.vn",
                            IsLocked = false,
                            Name = "Nguyễn Văn A",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 0
                        },
                        new
                        {
                            Id = "u8",
                            Department = "HR",
                            Email = "employee2@company.vn",
                            IsLocked = false,
                            Name = "Trần Thị B",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            RequirePasswordChange = false,
                            Role = 0
                        });
                });

            modelBuilder.Entity("HoldMaintenance.Api.Entities.AssetAssignment", b =>
                {
                    b.HasOne("HoldMaintenance.Api.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });
#pragma warning restore 612, 618
        }
    }
}
